### ISSUE TITLE
Network Configuration Decoding

### ISSUE THREAD

**Issue by craftycodie** [craftycodie/Sunrise-BlfTool#8]
The network configuration file contains thousands of variables. I've yet to properly decode/encode. I've got a rough model for it, i think encoding is broken though.

Grab a good netrwork configuration file (there's one in [here](https://github.com/craftycodie/Sunrise-Content/tree/main/json/storage/title/tracked/12070/default_hoppers)) and make sure that when reencoded, the contents of the netc chunk are the same)

**Comment by FWRB** [comment]
Hey Codie,

Was curious if this had this been addressed any further since originally noted? I've had no luck using BlfTool on any network_configuration_*.bin so far and assumed not, but wanted to dig a bit further on the networking side after dabbling in hopper settings.

**Comment by craftycodie** [comment]
nah i haven't dug into em

**Comment by FWRB** [comment]
No worries! Going to see if I can muster anything new on that front then, but not holding my breath. Thanks!
